version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-extractor-nest
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    volumes:
      - './src:/app/src'
